package BCNNM_DSL.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Cell = 0;
  public static final int Space = 1;
  public static final int SpikingCell = 2;
  public static final int StemCell = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x9edcd71856d444c5L, 0xae868ea31c5d7fbbL);
    builder.put(0x3831396a57ca6a5dL, Cell);
    builder.put(0x3831396a57cb195fL, Space);
    builder.put(0x3831396a57cb1957L, SpikingCell);
    builder.put(0x3831396a57cb18ebL, StemCell);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
